#!/usr/bin/env python3
"""Run a local verification loop before commit/PR.

Workflow:
1) Static quality checks
2) Test suite and coverage
3) Optional localhost Streamlit smoke check
4) Regenerate CLAUDE.md
5) Write success stamp for commit hook checks
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import time
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import URLError
from urllib.request import urlopen

PROJECT_ROOT = Path(__file__).resolve().parent.parent
VERIFY_STATE_PATH = PROJECT_ROOT / ".verification" / "last_verify_success.json"


def run_step(label: str, command: list[str]) -> None:
    """Run one verification step and fail fast on error."""
    print(f"\n[verify] {label}")
    print(f"[verify] $ {' '.join(command)}")
    subprocess.run(command, cwd=PROJECT_ROOT, check=True)


def get_git_output(*args: str) -> str:
    """Return git command output, or empty string when unavailable."""
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=PROJECT_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def normalized_changed_files() -> list[str]:
    """Return changed file paths without staged/unstaged status prefixes."""
    lines = get_git_output("status", "--porcelain").splitlines()
    paths: set[str] = set()
    for line in lines:
        if len(line) < 4:
            continue
        # Porcelain line format starts with 2-char XY status + space + path.
        raw_path = line[3:].strip()
        if " -> " in raw_path:
            raw_path = raw_path.split(" -> ", maxsplit=1)[1].strip()
        if raw_path:
            paths.add(raw_path)
    return sorted(paths)


def current_coverage_from_xml() -> str:
    """Read total coverage from coverage.xml generated by pytest-cov."""
    coverage_xml = PROJECT_ROOT / "coverage.xml"
    if not coverage_xml.exists():
        return "unknown"
    try:
        root = ET.parse(coverage_xml).getroot()
        line_rate = root.attrib.get("line-rate")
        if line_rate is None:
            return "unknown"
        return f"{float(line_rate) * 100:.2f}%"
    except (ET.ParseError, ValueError):
        return "unknown"


def check_localhost(url: str, timeout_seconds: int) -> bool:
    """Return True when localhost responds with a 2xx/3xx status."""
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        try:
            with urlopen(url, timeout=2) as response:
                if 200 <= response.status < 400:
                    return True
        except URLError:
            time.sleep(1)
    return False


def smoke_test_streamlit(port: int, timeout_seconds: int) -> None:
    """Verify Streamlit serves the app on localhost."""
    url = f"http://127.0.0.1:{port}"
    print(f"\n[verify] localhost smoke check on {url}")

    # Reuse an existing local server if already available.
    if check_localhost(url, timeout_seconds=3):
        print("[verify] existing local Streamlit server is healthy")
        return

    command = [
        sys.executable,
        "-m",
        "streamlit",
        "run",
        "app.py",
        "--server.headless",
        "true",
        "--server.port",
        str(port),
        "--browser.gatherUsageStats",
        "false",
    ]

    process = subprocess.Popen(command, cwd=PROJECT_ROOT, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        if not check_localhost(url, timeout_seconds=timeout_seconds):
            raise RuntimeError(f"Streamlit failed localhost smoke check at {url} in {timeout_seconds}s")
        print("[verify] localhost smoke check passed")
    finally:
        process.terminate()
        try:
            process.wait(timeout=5)
        except subprocess.TimeoutExpired:
            process.kill()


def write_success_stamp() -> None:
    """Persist the latest successful verification timestamp."""
    VERIFY_STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    changed_files = normalized_changed_files()
    payload = {
        "verified_at_utc": datetime.now(timezone.utc).isoformat(),
        "python": sys.version.split()[0],
        "workflow": "verify_loop",
        "git_head": get_git_output("rev-parse", "HEAD"),
        "changed_files_hash": hashlib.sha256("\n".join(changed_files).encode("utf-8")).hexdigest(),
        "coverage": current_coverage_from_xml(),
    }
    VERIFY_STATE_PATH.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print(f"[verify] wrote success stamp to {VERIFY_STATE_PATH}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run quality/test/docs verification loop.")
    parser.add_argument(
        "--localhost-check",
        action="store_true",
        help="Run a localhost Streamlit smoke check after tests.",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8502,
        help="Port used for localhost smoke check when starting Streamlit.",
    )
    parser.add_argument(
        "--timeout-seconds",
        type=int,
        default=45,
        help="Timeout in seconds for localhost smoke check startup.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Expand lint/type checks to tests, app, and scripts.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    lint_paths = ["utils", "community_pulse", "components"]
    if args.strict:
        lint_paths.extend(["tests", "app.py", "scripts"])

    run_step(
        "black --check",
        [
            sys.executable,
            "-m",
            "black",
            "--check",
            "--line-length=120",
            "utils",
            "community_pulse",
            "components",
            "tests",
            "app.py",
            "scripts",
        ],
    )
    run_step(
        "flake8",
        [
            sys.executable,
            "-m",
            "flake8",
            *lint_paths,
            "--max-line-length=120",
            "--ignore=E203,W503,E501",
        ],
    )
    run_step(
        "mypy",
        [sys.executable, "-m", "mypy", *lint_paths, "--ignore-missing-imports"],
    )
    run_step(
        "pytest + coverage",
        [
            sys.executable,
            "-m",
            "pytest",
            "tests",
            "-v",
            "--tb=short",
            "--cov=utils",
            "--cov=community_pulse",
            "--cov-report=term",
            "--cov-report=xml",
            "--cov-fail-under=55",
        ],
    )
    if args.localhost_check:
        smoke_test_streamlit(args.port, args.timeout_seconds)
    run_step("regenerate CLAUDE.md", [sys.executable, "scripts/update_claude_md.py"])
    write_success_stamp()
    print("\n[verify] verification loop completed successfully")


if __name__ == "__main__":
    main()
